config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users

  resources :posts do
  	member do

  		get "like", to: "posts#upvote"
  		get "dislike", to: "posts#downvote"
  	end

  	collection do
  		get 'all'
  	end
  	resources :comments
  end

  root to: 'posts#index'
 
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
  belongs_to :user
 validates :content, :presence => true
end

app/models/post.rb
class Post < ActiveRecord::Base
	acts_as_votable
	belongs_to :user
	has_many :comments, dependent: :destroy
	validates :title, :presence => true
 	validates :link, :presence => true
 	validates :description, :presence => true

 	has_attached_file :image, styles: { medium: "700x500#", small: "350x250#", thumb: "150x150#" }
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :posts
  has_many :comments
  before_create :make_admin_user

  private

  def make_admin_user 
  	if self.name == "jocelyn alsdorf"
  		self.admin = 'true'
  	end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

	before_filter :configure_permitted_parameters, if: :devise_controller?

	protected

	def configure_permitted_parameters
	  devise_parameter_sanitizer.for(:sign_up) << :name
	  devise_parameter_sanitizer.for(:account_update) << :name
	end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	before_action :authenticate_user!
	
	def error

	render :error
	end

	def destroy
		@comment = Comment.find(params[:id])
		@comment.destroy	
		redirect_to root_path
	end

	def show
		@comment = Comment.find(params[:id])
		@post = Post.find(params[:post_id])
	end

	def edit
		@post = Post.find(params[:post_id])
			@comment = Comment.find(params[:id])
	end

	def update
			@post = Post.find(params[:post_id])
			@comment = Comment.find(params[:id])
		if @comment.update(comment_params)
			redirect_to @post
		else
			render :error
		end
	end

	def create
		@post = Post.find(params[:post_id])
		@comment = Comment.create(params[:comment].permit(:content))
		@comment.user_id = current_user.id
		@comment.post_id = @post.id
		if @comment.save
			redirect_to post_path(@post)
		else
			render :error
		end
	end

	def comment_params
		params.require(:comment).permit(:content)
	end

end

app/controllers/posts_controller.rb
class PostsController <  ApplicationController
before_action :find_post, only: [:show, :edit, :update, :destroy, :upvote, :downvote]
before_action :authenticate_user!, except: [:index, :show]

	def index
		@posts = Post.all.order("created_at DESC")
	end

	def show
		@comments = Comment.where(post_id: @post)
	end

	def new
		@post = current_user.posts.build
	end

	def create
		@post = current_user.posts.build(post_params)

		if @post.save
			redirect_to @post
		else
			render :new
		end
	end

	def edit
	end

	def update
		if @post.update(post_params)
			redirect_to @post
		else
			render :edit
		end
	end

	def destroy
		@post.destroy
		redirect_to root_path
	end

	def upvote
		@post.upvote_by current_user
		redirect_to :back
	end

	def downvote
		@post.downvote_from current_user
		redirect_to :back
	end

	def all
		@posts = Post.all

	end

private

	def find_post
			@post = Post.find(params[:id])
	end

	def post_params
		params.require(:post).permit(:title, :link, :description, :image)
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/comments/_form.html.erb
<%= render "layouts/errors", :object => @post %>
<div class="container">
<h3>Leave a Comment</h3>


<%= simple_form_for [@post, @post.comments.build] do |f| %>
	<%= f.input :content, label: "Reply to thread" %>
  <%= f.button :submit, class: "button" %>
<% end %>


</div>

app/views/comments/edit.html.erb
<% content_for :title, "Space Show | Edit Comment" %>

<h1 class="form-titles">Edit My Comment</h1>

<%= simple_form_for  [@post, @comment] do |f| %>
	<%= f.input :content %>
  <%= f.button :submit, class: "button" %>
<% end %>

<%= link_to "Back", root_path %>

app/views/comments/error.html.erb
<h1> What do you think you are doing??!!! You cannot enter a blank comment!!Geez!</h1>


<p><%= link_to "home", root_path %></p>

app/views/comments/show.html.erb
<% content_for :title, "Space Show | Comment" %>

<%= @comment.content %>
<% if (@comment.user == current_user) || (current_user && current_user.admin?)  %>
	<p><%= link_to "Edit", edit_post_comment_path(@post, @comment) %></p>
	<p><%= link_to "Delete My Comment", post_comment_path(@post, @comment), method: 
										:delete, data: {confirm: "Are you sure?"} %></p>

<% end %>
<p><%= link_to "home", root_path %></p>

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
  <h3>These errors need fixed:</h3>
  <ul class="errors">
    <% object.errors.full_messages.each do |message| %>
      <li ><%= message %></li>
    <% end %>
  </ul>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title> <%= yield(:title) %></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="container">
<nav class="navbar navbar-default navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">Space Show</a>
    </div>
    <div class="collapse navbar-collapse navbar-right">
       <%= link_to "Logout", destroy_user_session_path, method: :delete %>
    		<% if user_signed_in? %>
    		  <span class="session-info">Logged in as <%= link_to current_user.name, edit_user_registration_path %></span>
        
    		 
    		<% else %>
    		 	 <span class="session-info"><%= link_to "Sign in", new_user_session_path, class: "button"%> or
    		   <%= link_to "Sign Up", new_user_registration_path, class: "button" %></span>
    		<% end %>
    
      <ul class="nav navbar-nav navbar-left">
        <li><%= link_to "Add New Post", new_post_path %></li>
      </ul>
    </div>
  </div>
</nav>

<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>
	<%= yield %>
</div>

</body>
</html>

app/views/posts/_form.html.erb
<%= render "layouts/errors", :object => @post %>
<div class="container">
<h2>Add new post</h2>


<%= simple_form_for @post do |f| %>
	<%= f.input :image %>
  <%= f.input :title %>
  <%= f.input :link %>
  <%= f.input :description %>
  <%= f.button :submit %>
<% end %>


</div>

app/views/posts/all.html.erb
<div class="row">
<div class="col-lg-3"></div>
	<div class="col-lg-6 center-block well">
		<h2>Admin Page</h2>
		<h3>Hello there, boss lady!</h3>
		<p>View all current posts, users, and comments</p>
		<div class="left-block">
		<% @posts.each do |post| %>
		<p class="all-user-list"><strong>User</strong> <%= post.user.name %> <strong>wrote: </strong><%= post.title %> <strong>on: </strong> <%= post.created_at.strftime('%b %d, %Y')%></p>
		<% end %>
	</div>
	<div class="col-lg-3"></div>
</div>

app/views/posts/edit.html.erb
<% content_for :title, "Space Show | Edit Post" %>

<h1 class="form-titles">EditPost</h1>

<%= render 'form' %>

<%= link_to "Back", root_path %>

app/views/posts/index.html.erb
<% content_for :title, "Space Show | New Post" %>


<div class="row">
	<div class="col-lg-12">
		<div class="jumbotron">
			<div class="container">
			<% if current_user && current_user.admin? %>
			<h4>Welcome Jocelyn, our favorite and only admin!</h4>
			<%= link_to "See Admin Page", all_posts_path %>
			<% else %>
			<h4>Welcome <%= current_user.name %>!</h4>
			<% end %>
			</div>
		</div>
	</div>
</div>
<div class="row">
		<div class="col-lg-12">
		  <% @posts.each do |post| %>
		  <div class="col-lg-4">
		   <%= link_to(image_tag post.image.url(:small))  %>
		   <p><%= link_to post.title, post_path(post) %></p>
		   <P><%= post.comments.count%> Comments</P>
		   <P><%= post.get_likes.size%>  <span class="glyphicon glyphicon-thumbs-up"></span></P>
		   </div>
		  <% end %>
			
		</div><!-- end of col 12 -->
</div><!-- end of row 2 -->
		<div class="row">
		<div class="col-lg-12">
			<p><%= link_to "Add Post", new_post_path %></p>
		</div>
	</div><!-- wnd of row2 -->

app/views/posts/new.html.erb
<% content_for :title, "Space Show | New Post" %>

<h1 class="form-titles">New Post</h1>

<%= render 'form' %>

<%= link_to "Back", root_path %>

app/views/posts/show.html.erb
<% content_for :title, "Space Show | New Post" %>
<div class="row">
	<div class="col-lg-1"></div>

		<div class="col-lg-10 well">

		<div class="post-img center-block"><%= image_tag @post.image.url(:medium) %></div>
		<h2 class="post-title"><%= @post.title %></h2>
		<p class="post-link"><%= @post.link %></p>
		<p class="post-description"><%= @post.description %></p>
		<p class="post-user">Posted By: <span class="fancy-text"><%= @post.user.name %></span></p>

		<p class="post-like"><%= @post.get_upvotes.size %>  <span class="glyphicon glyphicon-thumbs-up"></span> <span class="like-text"><%= link_to "Like this Posting", like_post_path(@post), method: :get %></span></p>
		<p class="post-like"><%= @post.get_downvotes.size%> <span class="glyphicon glyphicon-thumbs-down"></span> <span class="like-text"> <%=link_to "Dislike this Posting", dislike_post_path(@post), method: :get %></span></p>

	
		
		<% if (@post.user == current_user) || (current_user && current_user.admin?) %>
			<p><%= link_to "Edit", edit_post_path(@post) %></p>
			<p><%= link_to "Delete", post_path(@post), method: 
													:delete, data: {confirm: "Are you sure?"} %></p>
		<% end %>
				<p class="home-link"><%= link_to "home", root_path %></p>
			<div id="comment">
				<h3 class="comment-count"><%= pluralize(@post.comments.count, "Comment") %></h3>
				<% @comments.each do |comment| %>
				<p class="comment-name"><%= comment.user.name %></p>
				<p><%= link_to comment.content, post_comment_path(@post, comment) %></p>
				<% end %>
				<%= render 'comments/form' %>
			</div>

	

		</div><!-- end of col-10 -->
	<div class="col-lg-1"></div>
</div><!-- end of row-1 -->